<a href="https://colab.research.google.com/github/matheusvazdata/analise_exploratoria_de_dados_enem_2022/blob/main/SQL_no_notebook_com_conexao_e_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%pip install Sqlalchemy
%pip install sqlite3
%pip install cx_Oracle
%pip install Pyodbc

Requirement already satisfied: Sqlalchemy in /usr/local/lib/python3.10/dist-packages (2.0.36)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from Sqlalchemy) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from Sqlalchemy) (3.1.1)
ERROR: Could not find a version that satisfies the requirement sqlite3 (from versions: none)
ERROR: No matching distribution found for sqlite3
Requirement already satisfied: cx_Oracle in /usr/local/lib/python3.10/dist-packages (8.3.0)
Requirement already satisfied: Pyodbc in /usr/local/lib/python3.10/dist-packages (5.2.0)

# sqlite3

In [2]:
import sqlite3
import pandas as pd

In [3]:
query = "SELECT name FROM sqlite_master WHERE type='table'"

In [4]:
con = sqlite3.connect("/content/nba_salary.sqlite")
df_tables = pd.read_sql_query(query,con)
print(df_tables)

con.close()

                    name
0  NBA_season1718_salary
1          Seasons_Stats

In [7]:
# Ler o dataset utilizado para extrair apenas os jogadores com um salário maior que 10 milhões de dólares

value = 10_000_00

query = f'''
SELECT *
FROM NBA_season1718_salary
WHERE season17_18 > {value}
ORDER BY season17_18;
'''

con = sqlite3.connect("/content/nba_salary.sqlite")
df_salaries_greater_than_10000000 = pd.read_sql_query(query, con)
df_salaries_greater_than_10000000.head()

      X1              Player   Tm  season17_18
0  451.0  Livio Jean-Charles  SAS    1035200.0
1  450.0       Wesley Iwundu  ORL    1050000.0
2  449.0       Isaiah Canaan  PHO    1069308.0
3  448.0         Paul Pierce  LAC    1096080.0
4  447.0      Damyean Dotson  NYK    1100000.0

In [9]:
# Extrair as estatísticas desses jogadores correspondentes ao ano fornecido na tabela Season_Stats do ano 2017
year = 2017

query = f'''
SELECT *
FROM Seasons_Stats
WHERE Year = {year}
ORDER BY Year;
'''

con = sqlite3.connect("/content/nba_salary.sqlite")
df_stats_2017 = pd.read_sql_query(query, con)
df_stats_2017.head()

,X1,Year,Player,Pos,Age,Tm,G,GS,MP,PER,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,24096.0,2017.0,Alex Abrines,SG,23.0,OKC,68.0,NaN,1055.0,10.1,...,0.898,NaN,NaN,86.0,40.0,NaN,NaN,NaN,114.0,406.0
1,24097.0,2017.0,Quincy Acy,PF,26.0,TOT,38.0,1.0,558.0,11.8,...,0.750,NaN,NaN,115.0,18.0,NaN,NaN,NaN,67.0,222.0
2,24098.0,2017.0,Quincy Acy,PF,26.0,DAL,6.0,0.0,48.0,-1.4,...,0.667,NaN,NaN,8.0,0.0,0.0,0.0,NaN,9.0,13.0
3,24099.0,2017.0,Quincy Acy,PF,26.0,BRK,32.0,1.0,510.0,13.1,...,0.754,NaN,NaN,107.0,18.0,NaN,NaN,NaN,58.0,209.0
4,24100.0,2017.0,Steven Adams,C,23.0,OKC,80.0,NaN,2389.0,16.5,...,0.611,NaN,NaN,615.0,86.0,NaN,NaN,NaN,195.0,905.0

In [10]:
# Calcular a média total de pontos PTS, assistências AST e faltas pessoais PF da tabela Season_Stats.

query = f'''
SELECT AVG(PTS) AS PTS_AVG,
       AVG(AST) AS AST_AVG,
       AVG(PF) AS PF_AVG
FROM Seasons_Stats;
'''

con = sqlite3.connect("/content/nba_salary.sqlite")
df_stats_mean_PTS_AST_PF = pd.read_sql_query(query, con)
df_stats_mean_PTS_AST_PF.head()

     PTS_AVG     AST_AVG      PF_AVG
0  510.11635  114.852623  116.339222